### ISSUE TITLE
Using this code more generally

### ISSUE THREAD

**Issue by sama2689** [epigenelabs/pyComBat#15]
Hello and thank you for this excellent package. I am trying to use ComBat to correct for batch effects in clinical data instead of gene data, and was hoping to use this code to do it. I have 10 features for each sample in each batch, with 280 samples in batch 1 and 95 samples in batch 2. Currently each batch is a dataframe with rows representing individual samples and columns representing features.  What I want to do is apply combat to both of these batches so that batch effects are corrected for. Please note here that my features aren't gene expressions, but generic numerical features instead.

So, given this, I was going to implement pycombat. As pycombat assumes gene expression (rows) for each sample (columns), normalize features to 0 mean and unit variance, transpose my dataframes, , and then apply pycombat?

Thanks

**Comment by abdelkaderbehdenna** [comment]
Hello, and thank you for using pyComBat and for you very interesting question.

From the details you provide, I don't think I can answer your question for sure. However, I can tell you that the general framework of ComBat assumes that your data are normally distributed. If this is the case, you should be able to use pyComBat without any transformation to apply to your data. You can visually check (eg with a boxplot before/after pyComBat) if your batch effects seem to have been corrected.

I hope I answered your question, but don't hesitate to provide more details here if needed.

Best

**Comment by sama2689** [comment]
Hm, some of my features are normally distributed, but others are categorical values that are one hot encoded (e.g. gender). What should I make a boxplot of to check for batch effects, and what should I be on the lookout for visually to see that batch effects have been sucessfully corrected for?

**Comment by sama2689** [comment]
Would it work if I only applied combat to normally distributed features while letting the categorical features stay as they are? I do not think there are batch effects with the categorical variables

**Comment by abdelkaderbehdenna** [comment]
Hi,

It should indeed work in this context. You can keep the categorical variables as they are (and you can't do much about them anyway) and correct for batch effects on the normally distributed features.

Concerning the visual verification for the correction, you can check on the boxplot if the boxes are aligned after using pyComBat (you can see an example at [this address](https://epigenelabs.github.io/pyComBat/)).
