### ISSUE TITLE
No module named 'mpmath'

### ISSUE THREAD

**Issue by such3r** [epigenelabs/pyComBat#9]
Code:
> from combat.pycombat import pycombat

Causes:
> File ".../python3.8/site-packages/combat/pycombat.py", line 30, in <module>
>     import mpmath as mp
> ModuleNotFoundError: No module named 'mpmath'

**Comment by zangzelin** [comment]
try

pip install mpmath

**Comment by aryoepigene** [comment]
Thanks, @zangzelin for the solution. A simple installation of the dependency would definitely suffice, as suggested. We also updated our codebase to alleviate future dependency confusion. See #11
